language: rubyonrails
rvm:
- ruby-head
deploy:
  provider: heroku
  app: young-hollows-31889
  api_key:
    secure: kyl5PUb+vWHAZNyQYGuYkU03YHDL1PQeWtSvNZJueBFO/RgH2ApfQHWukil7o1rxrYfOH55iAqG+t93wceHOJU0+9/MiXCKBzecrP6c923pvEkuIFzFV7zTJDFZXsKfEbQfnmoluocR6u7ZkrWEzuhuMnKNfSnZY8RaeWXcYymudIvYpLlOF8cqj8ZzXQzbPiAU1RNyu0ZVv9oDvI1n+FBmYjevqGtRx5vuA3RDTWS/4EeY7L3jdftkDsgfd3+GrsAOCKzpxbznYs0+YnDOyGLLMhf053t94mPyEveWW4hQpyTeuJAhOvu1vHDW74SkPOnoBAnwNXGXq7rxTH0dPI7nWzZEF1EoLyusaPIuxMLf+lsll1Jzbxm86TwuxQXliqgNUdTn/3X4asgMwqhw7rzMQtUD3SIK2XbSjcG0titwfMo/cW1cOl+HA1pYOIa23kMx+A5AaBBrupyMkGwBACIrTCv3SFqeo+MQjMybzIuj0NTskEPF7uDLr1SnYqTDRYR97UVlIzDosvVzlUPS8YYW4/13xU/qTKvWKF24UEcAIW0UfEqG5CL+Uh7YqGiclgJnKPs5h8OxM56auBCxnONnxXiMvOoWmsuPZCHTFj6A8FV+hrTzlwGepRMpvGHU0O+Qg/WVSDN1dlsiE6WYVLRDU5TJ691uu+nRtRSuIFJw=
